application:
  name: crud-edacy-backend

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productsdb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect